version: "3.8"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: proektus-app:latest
    container_name: proektus_worker
    restart: on-failure
    tty: true
    env_file:
      - .env